-- Volunteer skills/interests vocabulary
CREATE TABLE IF NOT EXISTS volunteer_vocab (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  type TEXT NOT NULL CHECK (type IN ('skill','interest')),
  name TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (DATETIME('now')),
  UNIQUE(type, name COLLATE NOCASE)
);

INSERT OR IGNORE INTO volunteer_vocab (type, name) VALUES
  ('skill', 'Administrative Support'),
  ('skill', 'Childcare'),
  ('skill', 'Cooking'),
  ('skill', 'Data Entry'),
  ('skill', 'Driving'),
  ('skill', 'Event Setup'),
  ('skill', 'First Aid'),
  ('skill', 'Food Prep'),
  ('skill', 'Fundraising'),
  ('skill', 'Grant Writing'),
  ('skill', 'Inventory'),
  ('skill', 'Logistics'),
  ('skill', 'Mentoring'),
  ('skill', 'Outreach'),
  ('skill', 'Photography'),
  ('skill', 'Technology Support'),
  ('skill', 'Training'),
  ('skill', 'Translation'),
  ('skill', 'Tutoring'),
  ('interest', 'Administration'),
  ('interest', 'Advocacy'),
  ('interest', 'Communications'),
  ('interest', 'Community Meals'),
  ('interest', 'Cooking'),
  ('interest', 'Education'),
  ('interest', 'Emergency Response'),
  ('interest', 'Events'),
  ('interest', 'Food Pantry'),
  ('interest', 'Fundraising'),
  ('interest', 'Health and Wellness'),
  ('interest', 'Housing Support'),
  ('interest', 'Inventory'),
  ('interest', 'Mentoring'),
  ('interest', 'Outreach'),
  ('interest', 'Senior Support'),
  ('interest', 'Transportation'),
  ('interest', 'Tutoring'),
  ('interest', 'Youth Programs');
